### ISSUE TITLE
Perl source has not been committed

### ISSUE THREAD

**Issue by soren** [DeBos99/Math-RPN-Tiny#1]
The ``.gitignore`` ignores everything except 9 specific files that are included by negating the filename with the "!" prefix.

I would suggest adding filenames and patterns that should be ignored to the ``.gitignore`` file in stead, something like this:

```
MYMETA.json
MYMETA.yml
Makefile
Makefile.old
Math-RPN-Tiny-*.tar.gz
blib/
```

**Comment by DeBos99** [comment]
Sorry, I was changing repo and I didn't spot that.
